version: '3.8'
services:
  app:
    build: .
    image: brandlift-backend:latest
    working_dir: /usr/src/app
    environment:
      - MONGO_URL=mongodb://mongo:27017/nest
    ports:
      - '8000:8000'
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: nest
volumes:
  mongo_data:
