version: '3.9'
services:
  app:
    build: .
    image: brandlift-backend:latest
    working_dir: /usr/src/app
    environment:
      - MONGO_URL=mongodb://mongo:27017/nest
    ports:
      - '8000:8000'
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: nest
  db:
    build: 
      context: .docker/postgres     
    container_name: sass-db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  mongo_data:
  postgres_data:
